# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

python:
  version: 3.7
  install:
    - requirements: Python/docs/requirements.txt



# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: Python/docs/conf.py

# Build documentation with MkDocs
#mkdocs:
#  configuration: mkdocs.yml

# Optionally build your docs in additional formats such as PDF and ePub
# formats: all
